Fix missing stack_t in ucontext.h
A simple compile fails of this program:
  #include <ucontext.h>
  int test_type;
error: unknown type name 'stack_t'

ucontext.h needs to declare sigset_t and stack_t (if they are
not already declared) so struct ucontext can use them.

r Please enter the commit message for your changes. Lines starting